# Changes here will be overwritten by Copier
_commit: v1.8.9
_src_path: https://github.com/phil65/copier-phil65.git
author_email: philipptemminghoff@googlemail.com
author_fullname: Philipp Temminghoff
author_username: phil65
copyright_date: '2024'
copyright_holder: Philipp Temminghoff
copyright_holder_email: philipptemminghoff@googlemail.com
libraries_use_pydantic: true
libraries_use_qt: false
project_description: Create OpenAI-compatible function schemas from python functions
project_name: Py2OpenAI
python_minimum_version: '3.12'
python_package_command_line_name: py2openai
python_package_distribution_name: py2openai
python_package_import_name: py2openai
repository_name: py2openai
repository_namespace: phil65
repository_provider: github.com

